version: "3"

services:

  db_omero:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "db_omero:/var/lib/postgresql/data"
      - "backup:/backups"

  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    environment:
      CONFIG_omero_db_host: db_omero
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6"
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web_prefix: "/omero"
      CONFIG_omero_web_static__url: "/omero/static/"
    networks:
      - omero
    ports:
      - "127.0.0.1:4080:4080"

networks:
  omero:

volumes:
  db_omero:
  omero:
    driver_opts:
      type: none
      device: /home/guillaume/data/OMERO
      o: bind
  backup:
    driver_opts:
      type: none
      device: /home/guillaume/data/backups/omero
      o: bind
