version: "3"

services:

  db_omero:
    image: "postgres:11"
    restart: always
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: XXX
    networks:
      - omero
    volumes:
      - "db_omero:/var/lib/postgresql/data"
      - "backup:/backups"

  omeroserver:
    image: "centuri/centuri-omero-server:latest"
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    env_file:
      - .env
    networks:
      - omero
    ports:
      - "4064:4064"
      - "4065:4065"
      - "4066:4066"
    volumes:
      - "omero:/OMERO"
      - "./certs:/etc/ssl/selfsigned:ro${VOLOPTS-}"
      - "teamimagerie:/mnt/teamimagerie"
  omeroweb:
    image: "openmicroscopy/omero-web-standalone:latest"
    restart: always
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web__check_version: "false"
      CONFIG_omero_web_secure: "true"
    networks:
      - omero
    ports:
      - "127.0.0.1:4080:4080"

networks:
  omero:

volumes:
  db_omero:
  omero:
    driver_opts:
      type: none
      device: XXX/data/OMERO
      o: bind
  backup:
    driver_opts:
      type: none
      device: XXX/data/backups/omero
      o: bind
  teamimagerie:
    driver: local
    driver_opts:
      type: cifs
      o: ro,vers=1.0,cache=strict,username=XXX,password=XXX,addr=XXX,file_mode=0444,dir_mode=0555
      device: "//XX/XXXXX/"
