---

- hosts: server
  vars:
    secrets_path: centuri_secrets
    src_dir: "{{ ansible_facts['env']['HOME'] }}/Dev"

  vars_files:
  - "{{ secrets_path }}/clicket_config.json"

  tasks:
  - name: Create db user
    become: true
    become_user: postgres
    postgresql_user:
      name: "flicket"
      password: "{{ db_password }}"

  - name: Create db
    become: true
    become_user: postgres
    postgresql_db:
      name: "flicket"
      owner: "flicket"

  - name: Grab clicket
    git:
      repo: https://github.com/centuri-engineering/clicket.git
      dest: "{{ src_dir }}/clicket"

  - name: Copy config
    copy:
      src: "{{ secrets_path }}/clicket_config.json"
      dest: "{{ src_dir }}/clicket/config.json"

  - name: Install dependencies
    pip:
      virtualenv: "{{ src_dir }}/venv"
      virtualenv_command: python3 -m venv
      requirements: "{{ src_dir }}/clicket/requirements.txt"

  - name: Run the app
    gunicorn:
      app: wsgi:app
      conf: "{{ src_dir }}/clicket/gunicorn.conf.py"
      virtualenv: "{{ src_dir }}/venv"
      chdir: "{{ src_dir }}/clicket"
