---
- hosts: server

  tasks:
  - name: Stop omero server
    docker_container:
      name: omeroserver
      state: stopped

  - name: Stop omero web
    docker_container:
      name: omeroweb
      state: stopped

  - name: Start database
    docker_container:
      name: database
      state: started

  - name: Drop default database
    command: docker exec database dropdb -U omero omero

  - name: Create empty database
    command: docker exec database createdb -U omero omero

  - name: Restore dumped database
    command: docker exec database psql -U omero -d omero -f /backups/omero.sql
