---
- hosts: server
  vars:
    secrets_path: centuri_secrets
  vars_files:
  - "{{ secrets_path }}/omero_vars.yml"

  tasks:
  - name: Create db volume
    docker_volume:
      name: database

  - name: Create server volume
    docker_volume:
      name: omero
      driver_options:
        type: none
        device: "{{ data_path }}/OMERO"
        o: bind

  - name: Create backup volume
    docker_volume:
      name: backup
      driver_options:
        type: none
        device: "{{ backup_path }}"
        o: bind

  - name: Create network
    docker_network:
      name: omero

  - name: Run database
    docker_container:
      name: database
      restart_policy: unless-stopped
      image: 'postgres:11'
      env:
        POSTGRES_USER: "omero"
        POSTGRES_DB: "omero"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
      networks:
        - name: "omero"
      volumes:
        - "database:/var/lib/postgresql/data"
        - "backup:/backups"

  - name: Run omero server
    docker_container:
      name: 'omeroserver'
      restart_policy: unless-stopped
      image: "openmicroscopy/omero-server:5.6"
      env:
        CONFIG_omero_db_host: "database"
        CONFIG_omero_db_user: "omero"
        CONFIG_omero_db_pass:  "{{ postgres_password }}"
        CONFIG_omero_db_name: "omero"
        ROOTPASS: "{{ rootpass }}"
      networks:
        - name: "omero"
      published_ports:
        - "4063:4063"
        - "4064:4064"
      volumes:
        - "omero:/OMERO"

  - name: Run omero web
    docker_container:
      name: 'omeroweb'
      restart_policy: unless-stopped
      image: "openmicroscopy/omero-web-standalone:5.6"
      env:
        OMEROHOST: "omeroserver"
      networks:
        - name: omero
      published_ports:
        - "127.0.0.1:4080:4080"
